# Generated by Django 4.1.3 on 2022-11-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('long_description', models.TextField()),
                ('image', models.ImageField(upload_to='uploads/')),
                ('engine_language', models.CharField(max_length=255)),
                ('operating_system', models.CharField(max_length=255)),
                ('last_date_updated', models.DateField()),
                ('project_type', models.CharField(max_length=255)),
                ('tags', models.CharField(max_length=255)),
                ('repository_link', models.URLField()),
                ('external_link', models.URLField()),
                ('itch_link', models.URLField()),
                ('play_link', models.URLField()),
                ('ordinal', models.IntegerField()),
            ],
        ),
    ]
